#!/bin/bash
set -e

# =============================================================================
# Moodle 5.x Docker Entrypoint
# Downloads Moodle on first run, generates config.php from environment
# =============================================================================

# Configuration
MOODLE_VERSION="${MOODLE_VERSION:-5.1.2}"
INSTALL_DIR="/var/www/html"
VERSION_FILE="${INSTALL_DIR}/.moodle-version"
INSTALLED_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")

# Logging helper
log() {
    echo "[moodle-entrypoint] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# Skip bootstrap for cron container
if [ "${MOODLE_SKIP_BOOTSTRAP:-false}" = "true" ]; then
    log "MOODLE_SKIP_BOOTSTRAP=true, skipping bootstrap"
    exec "$@"
fi

# =============================================================================
# Moodle Download and Installation
# =============================================================================

backup_user_plugins() {
    log "Backing up user plugins..."
    mkdir -p /tmp/plugins_backup

    # Plugin directories that may contain user additions
    local plugin_types="mod local blocks theme auth enrol report question format"

    for ptype in $plugin_types; do
        local src_dir="$INSTALL_DIR/$ptype"
        if [ -d "$src_dir" ]; then
            mkdir -p "/tmp/plugins_backup/$ptype"
            # Copy all plugins (we'll filter core vs user later if needed)
            cp -r "$src_dir"/* "/tmp/plugins_backup/$ptype/" 2>/dev/null || true
        fi
    done

    log "Plugin backup complete"
}

restore_user_plugins() {
    log "Restoring user plugins..."

    local plugin_types="mod local blocks theme auth enrol report question format"

    for ptype in $plugin_types; do
        local backup_dir="/tmp/plugins_backup/$ptype"
        local dest_dir="$INSTALL_DIR/$ptype"

        if [ -d "$backup_dir" ]; then
            # Use cp -n to not overwrite existing (core) plugins
            cp -rn "$backup_dir"/* "$dest_dir/" 2>/dev/null || true
        fi
    done

    rm -rf /tmp/plugins_backup
    log "Plugin restore complete"
}

download_moodle() {
    local version="$1"

    # Extract major.minor for stable branch (e.g., 5.1.2 -> 501)
    local major=$(echo "$version" | cut -d. -f1)
    local minor=$(echo "$version" | cut -d. -f2)
    local stable_branch="${major}0${minor}"

    log "Downloading Moodle ${version} (stable${stable_branch})..."

    # Backup existing plugins if upgrading
    if [ -d "$INSTALL_DIR/lib" ]; then
        backup_user_plugins
    fi

    # Download Moodle
    local download_url="https://download.moodle.org/download.php/direct/stable${stable_branch}/moodle-${version}.tgz"
    log "Download URL: $download_url"

    # Download to temp and extract
    local temp_file="/tmp/moodle-${version}.tgz"
    curl -fSL "$download_url" -o "$temp_file"

    # Extract (strip the moodle-X.Y.Z directory)
    tar -xzf "$temp_file" -C "$INSTALL_DIR" --strip-components=1
    rm -f "$temp_file"

    # Restore user plugins if we had any
    if [ -d "/tmp/plugins_backup" ]; then
        restore_user_plugins
    fi

    # Mark installed version
    echo "$version" > "$VERSION_FILE"

    log "Moodle ${version} installed successfully"
}

# =============================================================================
# Config Generation
# =============================================================================

generate_config() {
    log "Generating config.php from environment..."

    # Determine SSL proxy setting (convert to PHP boolean)
    local ssl_proxy_php="false"
    if [ "${SSL_PROXY:-false}" = "true" ]; then
        ssl_proxy_php="true"
    fi

    cat > "${INSTALL_DIR}/config.php" <<EOFCONFIG
<?php
// Moodle configuration file - auto-generated by Docker entrypoint
// Do not edit directly - configure via environment variables

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

// =============================================================================
// Database Settings
// =============================================================================
\$CFG->dbtype    = '${DB_TYPE:-mariadb}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${DB_HOST:-database}';
\$CFG->dbname    = '${DB_NAME:-moodle}';
\$CFG->dbuser    = '${DB_USER:-moodle}';
\$CFG->dbpass    = '${DB_PASSWORD}';
\$CFG->prefix    = '${DB_PREFIX:-mdl_}';
\$CFG->dboptions = [
    'dbcollation' => 'utf8mb4_unicode_ci',
];

// =============================================================================
// Site Settings
// =============================================================================
\$CFG->wwwroot   = '${MOODLE_URL:-http://localhost}';
\$CFG->dataroot  = '/var/moodledata';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02775;

// =============================================================================
// Session Handling (Valkey/Redis)
// =============================================================================
\$CFG->session_handler_class = '\core\session\redis';
\$CFG->session_redis_host = '${VALKEY_HOST:-valkey}';
\$CFG->session_redis_port = ${VALKEY_PORT:-6379};
\$CFG->session_redis_auth = '${VALKEY_PASSWORD:-}';
\$CFG->session_redis_database = 0;
\$CFG->session_redis_prefix = 'mdl_sess_';
\$CFG->session_redis_acquire_lock_timeout = 120;
\$CFG->session_redis_lock_expire = 7200;

// =============================================================================
// Reverse Proxy Settings
// =============================================================================
\$CFG->reverseproxy = true;
\$CFG->sslproxy = ${ssl_proxy_php};

// =============================================================================
// Email Settings
// =============================================================================
\$CFG->smtphosts = '${SMTP_HOST:-mailpit}:${SMTP_PORT:-1025}';
\$CFG->noreplyaddress = '${SMTP_NOREPLY:-noreply@example.com}';

// =============================================================================
// Performance Settings
// =============================================================================
\$CFG->localcachedir = '/tmp/moodle_cache';

// =============================================================================
// Security Settings
// =============================================================================
\$CFG->passwordpolicy = true;
\$CFG->cronclionly = true;
\$CFG->cronremotepassword = '';

// =============================================================================
// Debug Settings (controlled by environment)
// =============================================================================
if (getenv('MOODLE_DEBUG') === 'true') {
    @error_reporting(E_ALL | E_STRICT);
    @ini_set('display_errors', '1');
    \$CFG->debug = (E_ALL | E_STRICT);
    \$CFG->debugdisplay = 1;
}

require_once(__DIR__ . '/lib/setup.php');
EOFCONFIG

    log "config.php generated"
}

# =============================================================================
# Permissions
# =============================================================================

fix_permissions() {
    log "Fixing permissions..."

    # Ensure moodledata is writable
    if [ -d /var/moodledata ]; then
        chown -R www-data:www-data /var/moodledata 2>/dev/null || true
        chmod -R 0775 /var/moodledata 2>/dev/null || true
    fi

    # Ensure code directory is writable for plugin installs
    if [ -d "$INSTALL_DIR" ]; then
        chown -R www-data:www-data "$INSTALL_DIR" 2>/dev/null || true
    fi

    log "Permissions fixed"
}

# =============================================================================
# Main
# =============================================================================

log "Starting Moodle entrypoint..."
log "MOODLE_VERSION=$MOODLE_VERSION"
log "INSTALLED_VERSION=$INSTALLED_VERSION"

# Download/upgrade Moodle if needed
if [ "$INSTALLED_VERSION" != "$MOODLE_VERSION" ]; then
    download_moodle "$MOODLE_VERSION"
fi

# Always regenerate config (environment may have changed)
generate_config

# Fix permissions
fix_permissions

log "Bootstrap complete, starting: $@"
exec "$@"
