#!/bin/bash
set -e

# =============================================================================
# Moodle 5.x Docker Entrypoint
# Installs the Moodle sources baked into the image, generates config.php from
# environment
# =============================================================================

# Configuration
DIST_DIR="/opt/moodle-dist"
IMAGE_VERSION=$(cat "${DIST_DIR}/.moodle-version" 2>/dev/null || echo "unknown")
MOODLE_VERSION="${MOODLE_VERSION:-$IMAGE_VERSION}"
INSTALL_DIR="/var/www/html"
VERSION_FILE="${INSTALL_DIR}/.moodle-version"
INSTALLED_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "none")

# Logging helper
log() {
    echo "[moodle-entrypoint] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# Skip bootstrap for cron container
if [ "${MOODLE_SKIP_BOOTSTRAP:-false}" = "true" ]; then
    log "MOODLE_SKIP_BOOTSTRAP=true, skipping bootstrap"
    exec "$@"
fi

# =============================================================================
# Moodle Download and Installation
# =============================================================================

backup_user_plugins() {
    log "Backing up user plugins..."
    mkdir -p /tmp/plugins_backup

    # Plugin directories that may contain user additions
    local plugin_types="mod local blocks theme auth enrol report question format"

    for ptype in $plugin_types; do
        local src_dir="$INSTALL_DIR/$ptype"
        if [ -d "$src_dir" ]; then
            mkdir -p "/tmp/plugins_backup/$ptype"
            # Copy all plugins (we'll filter core vs user later if needed)
            cp -r "$src_dir"/* "/tmp/plugins_backup/$ptype/" 2>/dev/null || true
        fi
    done

    log "Plugin backup complete"
}

restore_user_plugins() {
    log "Restoring user plugins..."

    local plugin_types="mod local blocks theme auth enrol report question format"

    for ptype in $plugin_types; do
        local backup_dir="/tmp/plugins_backup/$ptype"
        local dest_dir="$INSTALL_DIR/$ptype"

        if [ -d "$backup_dir" ]; then
            # Use cp -n to not overwrite existing (core) plugins
            cp -rn "$backup_dir"/* "$dest_dir/" 2>/dev/null || true
        fi
    done

    rm -rf /tmp/plugins_backup
    log "Plugin restore complete"
}

install_moodle() {
    local version="$1"

    log "Installing Moodle ${version} from image (${DIST_DIR})..."

    # Since Moodle 5.0 the web-facing tree lives under public/
    if [ ! -f "${DIST_DIR}/public/version.php" ]; then
        log "ERROR: no Moodle sources in this image at ${DIST_DIR}"
        exit 1
    fi

    # Backup existing plugins if upgrading
    if [ -d "$INSTALL_DIR/lib" ]; then
        backup_user_plugins
    fi

    # Copy the baked-in sources over the code volume
    cp -a "${DIST_DIR}/." "$INSTALL_DIR/"

    # Restore user plugins if we had any
    if [ -d "/tmp/plugins_backup" ]; then
        restore_user_plugins
    fi

    # Mark installed version
    echo "$version" > "$VERSION_FILE"

    log "Moodle ${version} installed successfully"
}

# =============================================================================
# Config Generation
# =============================================================================

generate_config() {
    log "Generating config.php from environment..."

    # Determine SSL proxy setting (convert to PHP boolean)
    local ssl_proxy_php="false"
    if [ "${SSL_PROXY:-false}" = "true" ]; then
        ssl_proxy_php="true"
    fi

    local reverse_proxy_php="false"
    if [ "${REVERSE_PROXY:-false}" = "true" ]; then
        reverse_proxy_php="true"
    fi

    local router_configured_php="false"
    if [ "${ROUTER_CONFIGURED:-true}" = "true" ]; then
        router_configured_php="true"
    fi

    cat > "${INSTALL_DIR}/config.php" <<EOFCONFIG
<?php
// Moodle configuration file - auto-generated by Docker entrypoint
// Do not edit directly - configure via environment variables

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

// =============================================================================
// Database Settings
// =============================================================================
\$CFG->dbtype    = '${DB_TYPE:-mariadb}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${DB_HOST:-database}';
\$CFG->dbname    = '${DB_NAME:-moodle}';
\$CFG->dbuser    = '${DB_USER:-moodle}';
\$CFG->dbpass    = '${DB_PASSWORD}';
\$CFG->prefix    = '${DB_PREFIX:-mdl_}';
\$CFG->dboptions = [
    'dbcollation' => 'utf8mb4_unicode_ci',
];

// =============================================================================
// Site Settings
// =============================================================================
\$CFG->wwwroot   = '${MOODLE_URL:-http://localhost}';
\$CFG->dataroot  = '/var/moodledata';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02775;

// =============================================================================
// Session Handling (Valkey/Redis)
// =============================================================================
\$CFG->session_handler_class = '\core\session\redis';
\$CFG->session_redis_host = '${VALKEY_HOST:-valkey}';
\$CFG->session_redis_port = ${VALKEY_PORT:-6379};
\$CFG->session_redis_auth = '${VALKEY_PASSWORD:-}';
\$CFG->session_redis_database = 0;
\$CFG->session_redis_prefix = 'mdl_sess_';
\$CFG->session_redis_acquire_lock_timeout = 120;
\$CFG->session_redis_lock_expire = 7200;

// =============================================================================
// Proxy Settings
//
// sslproxy is the one an SSL-terminating proxy needs: it tells Moodle the
// connection is https even though the proxy speaks http to this container.
//
// reverseproxy is a different switch - Moodle's own config-dist describes it
// as being for "advanced reverse proxy load balancing configurations" and for
// port forwarding. With it on, Moodle compares the request against wwwroot and
// aborts with "reverseproxyabused" when they differ, which is exactly what a
// plain TLS-terminating proxy in front of the same host produces. It is
// therefore separate, and off unless asked for.
// =============================================================================
\$CFG->sslproxy = ${ssl_proxy_php};
\$CFG->reverseproxy = ${reverse_proxy_php};

// =============================================================================
// Router
//
// Moodle serves routed paths through r.php. With routerconfigured on, it emits
// those paths without the /r.php prefix and expects the web server to rewrite
// anything that is not a real file to r.php - the nginx image in this repo
// does exactly that, which is why the default is on.
//
// The two halves only work together. routerconfigured off makes the router set
// its own base path to /r.php, so an unprefixed request no longer matches and
// comes back 404. Set ROUTER_CONFIGURED=false when fronting this image with a
// web server that has no such rewrite.
// =============================================================================
\$CFG->routerconfigured = ${router_configured_php};

// =============================================================================
// Security
//
// preventexecpath keeps the paths to helper binaries (ghostscript, unoconv,
// aspell and friends) out of the admin UI, so nobody with access to it can
// point Moodle at an arbitrary executable. They come from this file instead -
// add them here if the image ever ships any.
// =============================================================================
\$CFG->preventexecpath = true;

// =============================================================================
// Email Settings
// =============================================================================
\$CFG->smtphosts = '${SMTP_HOST:-mailpit}:${SMTP_PORT:-1025}';
\$CFG->noreplyaddress = '${SMTP_NOREPLY:-noreply@example.com}';

// =============================================================================
// Performance Settings
// =============================================================================
\$CFG->localcachedir = '/tmp/moodle_cache';

// =============================================================================
// Security Settings
// =============================================================================
\$CFG->passwordpolicy = true;
\$CFG->cronclionly = true;
\$CFG->cronremotepassword = '';

// =============================================================================
// Debug Settings (controlled by environment)
// =============================================================================
// E_STRICT is folded into E_ALL since PHP 8.0 and deprecated since 8.4, where
// naming it emits a deprecation notice before any header is sent - that alone
// pins the status at 200 and corrupts a JSON body.
if (getenv('MOODLE_DEBUG') === 'true') {
    @error_reporting(E_ALL);
    @ini_set('display_errors', '1');
    \$CFG->debug = E_ALL;
    \$CFG->debugdisplay = 1;
}

require_once(__DIR__ . '/lib/setup.php');
EOFCONFIG

    log "config.php generated"
}

# =============================================================================
# Permissions
# =============================================================================

fix_permissions() {
    log "Fixing permissions..."

    # Ensure moodledata is writable
    if [ -d /var/moodledata ]; then
        chown -R www-data:www-data /var/moodledata 2>/dev/null || true
        chmod -R 0775 /var/moodledata 2>/dev/null || true
    fi

    # Ensure code directory is writable for plugin installs
    if [ -d "$INSTALL_DIR" ]; then
        chown -R www-data:www-data "$INSTALL_DIR" 2>/dev/null || true
    fi

    log "Permissions fixed"
}

# =============================================================================
# Config Hardening
# =============================================================================

# fix_permissions hands the whole tree to www-data, which leaves config.php
# writable by the web user - the one file that must not be. Moodle's own
# security report flags it, and it is the obvious target for anything that
# manages to write through PHP. The entrypoint regenerates the file on every
# start as root, so nothing needs write access to it at runtime.
protect_config() {
    local written=0

    for config in "${INSTALL_DIR}/config.php" "${INSTALL_DIR}/public/config.php"; do
        [ -f "$config" ] || continue
        chown root:www-data "$config"
        chmod 0440 "$config"
        written=$((written + 1))
    done

    log "config.php is read-only for the web user (${written} file(s))"
}

# =============================================================================
# Composer Dependencies
# =============================================================================

# The image builds vendor/ and install_moodle copies it along with everything
# else, so a volume filled by this image has it. A volume filled by an older
# one does not, and nothing repairs that on a same-version start: the sources
# are only copied when the version changes. Moodle then reports "Composer
# installed data not found" in its environment check and anything relying on
# the autoloader breaks. Restore it rather than serve an install that is
# missing its dependencies.
ensure_vendor() {
    if [ -f "${INSTALL_DIR}/vendor/autoload.php" ]; then
        return 0
    fi

    if [ ! -f "${DIST_DIR}/vendor/autoload.php" ]; then
        log "ERROR: no vendor/ in this image at ${DIST_DIR} - rebuild it"
        exit 1
    fi

    log "vendor/ is missing from the code volume, restoring it from the image..."
    rm -rf "${INSTALL_DIR}/vendor"
    cp -a "${DIST_DIR}/vendor" "${INSTALL_DIR}/vendor"
    log "vendor/ restored"
}

# =============================================================================
# Database Upgrade
# =============================================================================

# Is this database already an installed Moodle? A fresh stack has an empty
# database until someone runs the installer, and upgrade.php cannot help there.
#
# Three outcomes, and they must stay apart: 0 installed, PROBE_EMPTY an empty
# database, anything else a probe that could not answer - an unreachable
# database aborts in config.php long before the table check. Folding the last
# two together would let a database outage look like a fresh install, skip the
# upgrade and serve whatever the code volume happens to hold.
PROBE_EMPTY=10
PROBE_OUTPUT=""

moodle_is_installed() {
    local probe="/tmp/moodle-installed-probe.php"
    local rc=0

    cat > "$probe" <<PHPPROBE
<?php
define('CLI_SCRIPT', true);
require('${INSTALL_DIR}/config.php');
exit(\$DB->get_manager()->table_exists('config') ? 0 : ${PROBE_EMPTY});
PHPPROBE

    chmod 0644 "$probe"
    # A "! cmd" condition would hand back the negated status, not the probe's,
    # so the exit code has to come out of a || list. The output is captured
    # rather than discarded: "probe exit 1" on its own tells an operator
    # nothing, and the reason it failed is exactly what they need. It goes into
    # a variable, not a file - www-data has no writable directory here that is
    # not part of the site.
    PROBE_OUTPUT=$(su -s /bin/sh -c "php '$probe' 2>&1" www-data) || rc=$?
    rm -f "$probe"
    return $rc
}

# Bring the database up to the version of the sources in this image.
#
# upgrade.php is idempotent: it exits 0 with "Moodle is already up to date"
# when there is nothing to do, so this runs on every start and only acts when
# the code moved ahead of the database. Without it the site answers every
# request with the "Upgrade Moodle database now" page until someone clicks
# through the admin UI.
upgrade_database() {
    if [ "${MOODLE_AUTO_UPGRADE:-true}" != "true" ]; then
        log "MOODLE_AUTO_UPGRADE is not true, skipping the database upgrade"
        return 0
    fi

    local probe_rc=0
    moodle_is_installed || probe_rc=$?

    if [ "$probe_rc" -eq "$PROBE_EMPTY" ]; then
        log "No installed Moodle database found, skipping the database upgrade"
        log "Run admin/cli/install_database.php once to create it"
        return 0
    fi

    if [ "$probe_rc" -ne 0 ]; then
        log "ERROR: cannot tell whether the database holds a Moodle install (probe exit ${probe_rc})"
        log "Refusing to serve a site whose database state is unknown. The probe said:"
        printf '%s\n' "$PROBE_OUTPUT" | sed -e 's/^/[moodle-entrypoint]   /' >&2
        exit 1
    fi

    log "Upgrading the database if needed..."
    if su -s /bin/sh -c "php ${INSTALL_DIR}/admin/cli/upgrade.php --non-interactive" www-data; then
        log "Database is up to date"
        return 0
    fi

    log "ERROR: the database upgrade failed - refusing to serve a half-upgraded site"
    exit 1
}

# =============================================================================
# Main
# =============================================================================

log "Starting Moodle entrypoint..."
log "MOODLE_VERSION=$MOODLE_VERSION"
log "IMAGE_VERSION=$IMAGE_VERSION"
log "INSTALLED_VERSION=$INSTALLED_VERSION"

# The sources ship with the image, so a differing MOODLE_VERSION cannot be
# honoured at runtime. Refuse instead of serving a version nobody asked for.
if [ "$MOODLE_VERSION" != "$IMAGE_VERSION" ]; then
    log "ERROR: MOODLE_VERSION=$MOODLE_VERSION, but this image carries $IMAGE_VERSION"
    log "Rebuild the image with --build-arg MOODLE_VERSION=$MOODLE_VERSION"
    exit 1
fi

# Install/upgrade Moodle if needed
if [ "$INSTALLED_VERSION" != "$MOODLE_VERSION" ]; then
    install_moodle "$MOODLE_VERSION"
fi

# A volume from an older image can be missing vendor/
ensure_vendor

# Always regenerate config (environment may have changed)
generate_config

# Fix permissions
fix_permissions

# ...then take the write bit off config.php again
protect_config

# Bring the database up to the code version before serving anything
upgrade_database

log "Bootstrap complete, starting: $*"
exec "$@"
